In [79]:
import pandas as pd

In [80]:
data_allocine = pd.read_csv("input_datasets/allocine.csv")
data_imdb = pd.read_csv("input_datasets/imdbmovies.csv")

In [81]:
# display(data_allocine.info())

In [82]:
# display(data_imdb.info())

formatage date :

In [83]:
import pandas as pd

# Diviser la colonne date_sortie_y en utilisant le mot-clé " au "
data_allocine['semaine_fr'] = data_allocine['semaine_fr'].str.split(' au ').str[0]

# Afficher les premières lignes pour vérification
# display(data_allocine.head())

# Fonction pour convertir le format de date
def convert_date_format(date_str):
    try:
        return pd.to_datetime(date_str).strftime('%d/%m/%Y')
    except:
        return None
    
# Appliquer la fonction pour convertir le format de date
data_imdb['date_sortie_y'] = data_imdb['date_sortie_y'].apply(convert_date_format)

# Afficher les premières lignes pour vérification
# display(data_imdb.head())

Gestion du Budget:

In [84]:
data_imdb['budget'] = data_imdb['budget'].str.replace(' \(estimated\)', '')

In [85]:
import pandas as pd

# Charger le dataset
data_imdb = pd.read_csv("input_datasets/imdbmovies.csv")

# Compter le nombre de lignes
nombre_de_lignes = len(data_imdb)

# Compter le nombre de '$' dans la colonne 'budget'
nombre_de_dollars = data_imdb['budget'].str.count('\$').sum()

# Remplacer tous les '$' par des chaînes vides pour ne garder que les autres symboles
budget_sans_dollars = data_imdb['budget'].str.replace('$', '')

# Afficher les résultats
print("Nombre de lignes dans la colonne 'budget':", nombre_de_lignes)
print("Nombre de '$' dans la colonne 'budget':", nombre_de_dollars)

Nombre de lignes dans la colonne 'budget': 2500
Nombre de '$' dans la colonne 'budget': 1880

In [86]:
import pandas as pd

# Charger le dataset
data_imdb = pd.read_csv("input_datasets/imdbmovies.csv")

# Utiliser des expressions régulières pour extraire les symboles monétaires différents de '$' avant les chiffres
autres_symboles = data_imdb['budget'].str.extract(r'([^$\d]+)\d+')

# Supprimer les lignes où le résultat de l'extraction est nul
autres_symboles = autres_symboles.dropna()

# Afficher les différentes combinaisons de symboles monétaires
print("Combinaisons de symboles monétaires avant les chiffres (différentes de '$'):")
print(autres_symboles[0].unique())

Combinaisons de symboles monétaires avant les chiffres (différentes de '$'):
[',' '£' '€' '₹' 'DEM\xa0' '¥' 'FRF\xa0' '₩' 'ATS\xa0' 'RUR\xa0' 'DKK\xa0'
 'CN¥' 'SEK\xa0' 'ITL\xa0']

In [87]:
import pandas as pd

# Définir le taux de conversion en dollars pour chaque devise
taux_de_conversion = {
    '£': 1.38,  # Livre sterling (taux de change actuel)
    '€': 1.10,  # Euro (taux de change actuel)
    '₹': 0.014,  # Roupie indienne (taux de change actuel)
    'DEM': 0.62,  # Deutsche Mark (taux de change historique)
    '¥': 0.0093,  # Yen japonais (taux de change actuel)
    'FRF': 0.18,  # Franc français (taux de change historique)
    '₩': 0.00089,  # Won sud-coréen (taux de change actuel)
    'ATS': 0.090,  # Schilling autrichien (taux de change historique)
    'RUR': 0.013,  # Rouble russe (taux de change actuel)
    'DKK': 0.16,  # Couronne danoise (taux de change actuel)
    'CN¥': 0.15,  # Yuan chinois (taux de change actuel)
    'SEK': 0.12,  # Couronne suédoise (taux de change actuel)
    'ITL': 0.00061  # Lire italienne (taux de change historique)
}

# Fonction pour convertir le budget en dollars
def convertir_en_dollars(row):
    symbole = row['budget'].split()[0]  # Extraire le symbole (premier mot de la chaîne)
    montant = float(row['budget'].split()[1].replace(',', ''))  # Extraire le montant et supprimer les virgules
    if symbole == '$':
        return montant  # Déjà en dollars
    elif symbole in taux_de_conversion:
        taux = taux_de_conversion[symbole]
        return montant * taux
    else:
        return None  # Impossible de convertir

# Appliquer la conversion
data_imdb['budget_en_dollars'] = data_imdb.apply(convertir_en_dollars, axis=1)

# Afficher les premières lignes pour vérification
print(data_imdb[['budget', 'budget_en_dollars']].head())

ValueError: could not convert string to float: '(estimated)'

In [ ]:
import pandas as pd

# Charger le dataset
data_imdb = pd.read_csv("input_datasets/imdbmovies.csv")

# Filtrer les films dont la monnaie commence par 'N'
films_monnaie_N = data_imdb[data_imdb['budget'].str.startswith('F')]

# Afficher les films sélectionnés
display(films_monnaie_N)

,annee,budget,casting_complet,casting_principal,date_sortie_x,director,duree,film_id,genre,genres,langue,nbre_vote,pays,pegi,popularite_score,scenaristes,score,titre,titre_france,date_sortie_y
875,1994,"FRF 115,000,000 (estimated)","Jean Reno,Gary Oldman,Natalie Portman,Danny Ai...","Luc Besson,Luc Besson,Stars",NaN,Luc Besson,1h 50m,tt0110413,NaN,"Action,Crime,Drama","English,Italian,French",1.2M,"France,United States",R,256,Luc Besson,8.5,Léon: The Professional,NaN,"September 14, 1994"
1601,1997,"FRF 75,210,000 (estimated)","Bruce Willis,Milla Jovovich,Gary Oldman,Ian Ho...","Luc Besson,Writers,Luc Besson",NaN,Luc Besson,2h 6m,tt0119116,NaN,"Action,Adventure,Sci-Fi","Arabic,Egyptian (Ancient),English,Swedish,German",505K,"France,United Kingdom,United States",PG-13,238,Luc Besson,7.6,The Fifth Element,NaN,"May 7, 1997"

In [ ]:
display(data_allocine)

,actors,director,entrees_fr,entrees_usa,image_urls,nationalite,semaine_fr,semaine_usa,studio,timing,title,titre_original
0,"Maxime Gasteuil,Zabou Breitman,Romain Lancry","Edouard Pluvieux,Lionel Dutemple,Edouard Pluvieux",126678,NaN,https://fr.web.img5.acsta.net/c_310_420/pictur...,france,06/03/2024,NaN,wild bunch distribution,0,14 jours pour aller mieux,pas de titre original
1,"Agnès Jaoui,William Lebghil,Salif Cissé","Julien Carpentier,Julien Carpentier,Benjamin G...",58613,NaN,https://fr.web.img4.acsta.net/c_310_420/pictur...,france,06/03/2024,NaN,kmbo,0,la vie de ma mère,pas de titre original
2,"Christian Friedel,Sandra Hüller,Johann Karthaus","Jonathan Glazer,Jonathan Glazer",239108,NaN,https://fr.web.img6.acsta.net/c_310_420/pictur...,u.s.a.,31 janvier,NaN,bac films,0,la zone d'intérêt,the zone of interest
3,"Audrey Lamy,Fabrice Eboué,Anouk Grinberg","Maxime Govare,Romain Choay,Maxime Govare,Romai...",136628,NaN,https://fr.web.img6.acsta.net/c_310_420/pictur...,france,13/03/2024,NaN,warner bros. france,0,heureux gagnants,pas de titre original
4,"Paola Cortellesi,Valerio Mastandrea,Romana Mag...","Paola Cortellesi,Paola Cortellesi,Furio Andreotti",145340,NaN,https://fr.web.img3.acsta.net/c_310_420/pictur...,italie,13/03/2024,NaN,universal pictures international france,0,il reste encore demain,c'è ancora domani
...,...,...,...,...,...,...,...,...,...,...,...,...
1721,"Joel Edgerton,Callum Turner,Peter Guinness","George Clooney,Mark L. Smith",8401000,NaN,https://fr.web.img6.acsta.net/c_310_420/img/99...,u.s.a.,29 décembre,NaN,NaN,0,ils étaient un seul homme,the boys in the boat
1722,"Hilary Swank,Alan Ritchson,Amy Acker","Jon Gunn,Kelly Fremon Craig",6500000,NaN,https://fr.web.img5.acsta.net/c_310_420/pictur...,u.s.a.,23/02/2024,NaN,NaN,0,ordinary angels,pas de titre original
1723,"Ariana DeBose,Chris Messina,Pilou Asbæk","Gabriela Cowperthwaite,Nick Shafir",3064583,NaN,https://fr.web.img5.acsta.net/c_310_420/pictur...,u.s.a.,19/01/2024,NaN,1 nomination,0,i.s.s.,pas de titre original
1724,"Chuku Modu,Kit Young,Safia Oakley-Green","Andrew Cumming,Ruth Greenberg",0,NaN,https://fr.web.img5.acsta.net/c_310_420/pictur...,grande-bretagne,09/02/2024,NaN,NaN,0,out of darkness,pas de titre original
1725,"Justice Smith,David Alan Grier,An-Li Bogan","Kobi Libii,Kobi Libii",1250000,NaN,https://fr.web.img6.acsta.net/c_310_420/pictur...,u.s.a.,15/03/2024,NaN,NaN,0,the american society of magical negroes,pas de titre original