In [30]:
import pandas as pd

In [31]:
data_allocine = pd.read_csv("../scrapper/infosfilmsallocine.csv")
data_target_allocine = pd.read_csv("../scrapper/releaseFrUsaAllocine.csv")

In [32]:
# Remplacer les valeurs manquantes dans les colonnes 'actors' et 'director' par des chaînes vides
data_allocine['actors'] = data_allocine['actors'].fillna('')
data_allocine['director'] = data_allocine['director'].fillna('')

# Diviser les colonnes 'actors' en listes d'acteurs
data_allocine['actors'] = data_allocine['actors'].apply(lambda x: x.split(',')[1:] if isinstance(x, str) else [])

# Diviser la colonne 'director' et supprimer le préfixe "Par" et "De"
data_allocine['director'] = data_allocine['director'].apply(lambda x: x.replace('Par,', '').replace('De,', '') if isinstance(x, str) else '')

# Diviser la colonne 'director' en une liste
data_allocine['director'] = data_allocine['director'].apply(lambda x: x.split(',') if isinstance(x, str) else [])

In [33]:
# suppresion de colones:
col_to_drop = ["image_urls"]
data_allocine = data_allocine.drop(col_to_drop, axis = 1)

In [34]:
# Fusionner les datasets sur la colonne 'film_title' et 'title'
merged_data = pd.merge(data_allocine, data_target_allocine[['film_title', 'entrees_fr']], left_on='title', right_on='film_title', how='left')

# Supprimer la colonne 'film_title' redondante
merged_data.drop(columns=['film_title'], inplace=True)

# Afficher le résultat
display(merged_data)

,actors,director,nationalite,studio,timing,title,titre_original,entrees_fr
0,"[Audrey Lamy, Fabrice Eboué, Anouk Grinberg]","[Maxime Govare, Romain Choay, Maxime Govare, R...",France,Warner Bros. France,1h 43min,Heureux gagnants,NaN,136 628
1,"[Leonie Benesch, Michael Klammer, Rafael Stach...","[İlker Çatak, İlker Çatak, Johannes Duncker]",Allemagne,Tandem,1h 39min,La Salle des profs,Das Lehrerzimmer,90 612
2,"[Paola Cortellesi, Valerio Mastandrea, Romana ...","[Paola Cortellesi, Paola Cortellesi, Furio And...",Italie,Universal Pictures International France,1h 58min,Il reste encore demain,C'è ancora domani,145 340
3,"[Timothée Chalamet, Rebecca Ferguson, Oscar Is...","[Denis Villeneuve, Jon Spaihts, Denis Villeneuve]",U.S.A.,Warner Bros. France,2h 36min,Dune,NaN,1 030 687
4,"[Raphaël Personnaz, Doria Tillier, Jeanne Bali...","[Anne Fontaine, Anne Fontaine, Claire Barré]",France,SND,2h 00min,Bolero,NaN,177 724
...,...,...,...,...,...,...,...,...
14621,[],[Teddy Wayne],U.S.A.,NaN,NaN,The Winner,NaN,NaN
14622,"[Eletricer Kache Hamisi, Bibi Swaleh, Bosco Ba...","[Damien Hauser, Damien Hauser]",Kenya,NaN,1h 31min,After the Long Rains,Baada ya masika,NaN
14623,"[Kate Watson, Michael DeVorzon, Eric Roberts]","[Jared Cohn, Jared Cohn, Naomi L. Selfman]",U.S.A.,NaN,1h 30min,Fiancée à un imposteur,Her Deadly Groom,NaN
14624,"[Tom Everett Scott, Ella Ballentine, Mia Maestro]","[Peter Benson (IV), Melissa Salmons]",U.S.A.,NaN,1h 30min,Ensemble à tout prix!,"Rise and Shine, Benedict Stone",NaN
14625,"[Chaley Rose, Nathan Witte, Rebecca Olson]","[Jessica Harmon, Elizabeth Hackett, Hilary Gal...",Canada,NaN,1h 30min,Le Bouquet de la mariée,My Best Friend's Bouquet,NaN

In [35]:
# Afficher le DataFrame et supprimer les lignes avec des valeurs vide

merged_data = merged_data.dropna()

display(merged_data)

,actors,director,nationalite,studio,timing,title,titre_original,entrees_fr
1,"[Leonie Benesch, Michael Klammer, Rafael Stach...","[İlker Çatak, İlker Çatak, Johannes Duncker]",Allemagne,Tandem,1h 39min,La Salle des profs,Das Lehrerzimmer,90 612
2,"[Paola Cortellesi, Valerio Mastandrea, Romana ...","[Paola Cortellesi, Paola Cortellesi, Furio And...",Italie,Universal Pictures International France,1h 58min,Il reste encore demain,C'è ancora domani,145 340
5,"[Timothée Chalamet, Zendaya, Rebecca Ferguson]","[Denis Villeneuve, Denis Villeneuve, Jon Spaihts]",U.S.A.,Warner Bros. France,2h 46min,Dune : Deuxième Partie,Dune: Part Two,1 383 999
7,"[Anthony Hopkins, Johnny Flynn, Helena Bonham ...","[James Hawes, Lucinda Coxon, Nick Drake]",Grande-Bretagne,SND,1h 49min,Une vie,One Life,456 390
12,"[Olivia Colman, Jessie Buckley, Anjana Vasan]","[Thea Sharrock, Jonny Sweet]",Grande-Bretagne,StudioCanal,1h 40min,Scandaleusement vôtre,Wicked Little Letters,51 921
...,...,...,...,...,...,...,...,...
4703,"[America Young, Greg Chun, Kirsten Day]","[Scott Pleydell-Pearce, Christopher Keenan, Ka...",U.S.A.,\n385 entrées\n,1h 00min,"Barbie : Grande Ville, Grands Rêves","Barbie: Big City, Big Dreams",391
4812,"[Lu Celeste, Wu Xiaoliang, Jiajia Wang]","[Liang Ming, Liang Ming]",Chine,ASC Distribution,1h 44min,Grand frère,Wisdom Tooth,414
4948,"[Leopold Pallua, Rosa Zant, Anna Fenderl]","[Arash T. Riahi, Arash T. Riahi]",Autriche,Les Films du Losange,1h 42min,Oskar et Lily,Ein bisschen bleiben wir noch,1 324
4988,"[Astrid Adverbe, Dimitra Kontou, Maritza Gonza...","[Pamela Varela, Pamela Varela]",France,Cinéma Saint-André des Arts,1h 28min,Le Voyage d'Ana,El Viaje de Ana,108
5239,"[Salman Khan, Disha Patani, Sapna Pabbi]","[Prabhu Deva, A.C. Mughil, Vijay Maurya]",Inde,Night ed films,1h 54min,Radhe,Radhe: Your Most Wanted Bhai,196

In [36]:
# Aplatir les colonnes contenant des listes d'acteurs
merged_data['num_actors'] = merged_data['actors'].apply(len)  # Nombre d'acteurs
merged_data['actor_1'] = merged_data['actors'].apply(lambda x: x[0] if len(x) >= 1 else None)
merged_data['actor_2'] = merged_data['actors'].apply(lambda x: x[1] if len(x) >= 2 else None)
merged_data['actor_3'] = merged_data['actors'].apply(lambda x: x[2] if len(x) >= 3 else None)
# merged_data['actor_4'] = merged_data['actors'].apply(lambda x: x[3] if len(x) >= 4 else None)

# Aplatir les colonnes contenant des listes de réalisateurs
merged_data['num_director'] = merged_data['director'].apply(len)  # Nombre de réalisateurs
merged_data['director_1'] = merged_data['director'].apply(lambda x: x[0] if len(x) >= 1 else None)
merged_data['director_2'] = merged_data['director'].apply(lambda x: x[1] if len(x) >= 2 else None)
merged_data['director_3'] = merged_data['director'].apply(lambda x: x[2] if len(x) >= 3 else None)
# merged_data['director_4'] = merged_data['director'].apply(lambda x: x[3] if len(x) >= 4 else None)

# Supprimer les colonnes originales avec des listes si nécessaire
merged_data.drop(columns=['actors', 'director'], inplace=True)

In [37]:
#suppresion de l'espace dans le nombre d'entree

merged_data['entrees_fr'] = merged_data['entrees_fr'].str.replace(' ', '').astype(int)

In [38]:
# Convertir le timing en minutes
def convert_timing(timing):
    timing_cleaned = timing.replace('min', '')  # Supprimer 'min' de la chaîne
    hours, minutes = map(int, timing_cleaned.split('h '))
    total_minutes = hours * 60 + minutes
    return total_minutes



merged_data['timing'] = merged_data['timing'].apply(convert_timing)

In [39]:
# display(merged_data)
# {' Allemagne': 0, ' Italie': 1, ' U.S.A.': 2, ' Grande-Bretagne': 3, ' Irlande': 4, ' Chine': 5, ' Jordanie': 6, ' Iran': 7, ' Corée du Sud': 8, ' Pologne': 9, ' Chili': 10, ' Belgique': 11, ' Japon': 12, ' Espagne': 13, ' Finlande': 14, ' Danemark': 15, ' Grèce': 16, ' Turquie': 17, ' Suède': 18, ' Australie': 19, ' Mongolie': 20, ' Russie': 21, ' Yemen': 22, ' France': 23, ' Suisse': 24, ' Canada': 25, ' Indonésie': 26, ' Ukraine': 27, ' Norvège': 28, ' kazakhstan': 29, ' Soudan': 30, ' Argentine': 31, ' Géorgie': 32, ' Bhoutan': 33, ' Lituanie': 34, ' Brésil': 35, ' Roumanie': 36, ' Hong-Kong': 37, ' Egypte': 38, ' Bosnie-Herzégovine': 39, ' Tunisie': 40, ' Hongrie': 41, ' Guatemala': 42, ' Islande': 43, ' Slovaquie': 44, ' Pérou': 45, ' Portugal': 46, ' Pays-Bas': 47, ' Colombie': 48, ' Luxembourg': 49, ' Autriche': 50, ' Palestine': 51, ' République tchèque': 52, ' Macédoine': 53, ' Inde': 54, ' Philippines': 55, ' Kosovo': 56, ' Bolivie': 57, ' Israël': 58, ' Liban': 59, ' Taïwan': 60, ' Algérie': 61, ' Cambodge': 62, ' Uruguay': 63, ' Thaïlande': 64, ' Lésotho': 65, ' Costa Rica': 66, ' Mexique': 67}
nationalities = merged_data['nationalite'].unique()
nationality_dict = {nationality: i for i, nationality in enumerate(nationalities)}
merged_data['nationalite'] = merged_data['nationalite'].map(nationality_dict)

In [40]:
#exportation du dataset netoye
display(merged_data)

merged_data.to_csv("datasets/allocine_cleaned.csv", index=None)

merged_data.to_pickle("datasets/dataset.pkl")

,nationalite,studio,timing,title,titre_original,entrees_fr,num_actors,actor_1,actor_2,actor_3,num_director,director_1,director_2,director_3
1,0,Tandem,99,La Salle des profs,Das Lehrerzimmer,90612,3,Leonie Benesch,Michael Klammer,Rafael Stachowiak,3,İlker Çatak,İlker Çatak,Johannes Duncker
2,1,Universal Pictures International France,118,Il reste encore demain,C'è ancora domani,145340,3,Paola Cortellesi,Valerio Mastandrea,Romana Maggiora Vergano,3,Paola Cortellesi,Paola Cortellesi,Furio Andreotti
5,2,Warner Bros. France,166,Dune : Deuxième Partie,Dune: Part Two,1383999,3,Timothée Chalamet,Zendaya,Rebecca Ferguson,3,Denis Villeneuve,Denis Villeneuve,Jon Spaihts
7,3,SND,109,Une vie,One Life,456390,3,Anthony Hopkins,Johnny Flynn,Helena Bonham Carter,3,James Hawes,Lucinda Coxon,Nick Drake
12,3,StudioCanal,100,Scandaleusement vôtre,Wicked Little Letters,51921,3,Olivia Colman,Jessie Buckley,Anjana Vasan,2,Thea Sharrock,Jonny Sweet,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4703,2,\n385 entrées\n,60,"Barbie : Grande Ville, Grands Rêves","Barbie: Big City, Big Dreams",391,3,America Young,Greg Chun,Kirsten Day,3,Scott Pleydell-Pearce,Christopher Keenan,Kate Splaine
4812,5,ASC Distribution,104,Grand frère,Wisdom Tooth,414,3,Lu Celeste,Wu Xiaoliang,Jiajia Wang,2,Liang Ming,Liang Ming,None
4948,50,Les Films du Losange,102,Oskar et Lily,Ein bisschen bleiben wir noch,1324,3,Leopold Pallua,Rosa Zant,Anna Fenderl,2,Arash T. Riahi,Arash T. Riahi,None
4988,23,Cinéma Saint-André des Arts,88,Le Voyage d'Ana,El Viaje de Ana,108,3,Astrid Adverbe,Dimitra Kontou,Maritza Gonzalez,2,Pamela Varela,Pamela Varela,None
5239,54,Night ed films,114,Radhe,Radhe: Your Most Wanted Bhai,196,3,Salman Khan,Disha Patani,Sapna Pabbi,3,Prabhu Deva,A.C. Mughil,Vijay Maurya