In [1]:
import pandas as pd

In [2]:
allocine_df = pd.read_csv('allocine.csv')
data_eda_df = pd.read_csv('imdb/dataEda.csv')

In [3]:
# Before proceeding with the merge, let's normalize the 'title' columns in both dataframes to ensure a higher match rate.
# We'll convert titles to lowercase and strip leading/trailing spaces as a basic normalization step.

allocine_df['title_normalized'] = allocine_df['titre_original'].str.lower().str.strip()
data_eda_df['title_normalized'] = data_eda_df['title'].str.lower().str.strip()

# Now, let's merge the two dataframes on the normalized title column.
merged_df = pd.merge(allocine_df, data_eda_df, on='title_normalized', suffixes=('_allocine', '_dataEda'))

# Display the first few rows of the merged dataframe to verify the merge and the structure of the merged data.
merged_df.head()

,actors,director_allocine,entrees_fr,entrees_usa,image_urls,nationalite,semaine_fr,semaine_usa,studio,timing,...,langue,nbre_vote,nombre_vote,pays,pegi,popularite_score,release_date_france,scenaristes,score,title_dataEda
0,"Yu-mi Jeong,Sun-kyun Lee,Kim Kum-Soon","Jason Yu,Jason Yu",48796,NaN,https://fr.web.img2.acsta.net/c_310_420/pictur...,corée du sud,21/02/2024 au 28/02/2024,NaN,the jokers / les bookmakers,0,...,English,NaN,0,United States,15m,No Popularity Score,NaN,Craig E. Serling,0.0,Jam
1,"Mia Goth,Jenna Ortega,Martin Henderson","Ti West,Ti West",31224,NaN,https://fr.web.img2.acsta.net/c_310_420/pictur...,u.s.a.,02/11/2022 au 9/11/2022,NaN,kinovista,0,...,English,NaN,170K,"United States,Canada",R,86,"November 2, 2022",Ti West,6.5,X
2,"Jorma Tommila,Aksel Hennie,Jack Doolan","Jalmari Helander,Jalmari Helander",44625,NaN,https://fr.web.img6.acsta.net/c_310_420/pictur...,finlande,21/06/2023 au 28/06/2023,NaN,snd,0,...,"English,Finnish",NaN,74K,"Finland,United Kingdom,United States",R,531,"April 10, 2023",Jalmari Helander,6.9,Sisu
3,"Ari McCarthy,Hamish Phillips,Sunny Johnson","Danny Philippou,Michael Philippou,Danny Philip...",187507,NaN,https://fr.web.img6.acsta.net/c_310_420/pictur...,australie,26 juillet au 2 août 2023,NaN,snd,0,...,"English,Greek",NaN,138K,"Australia,United Kingdom",R,240,"July 26, 2023",Danny Philippou,7.1,Talk to Me
4,"Patrick Wilson,Vera Farmiga,Ruairi O'Connor","Michael Chaves,David Leslie Johnson-McGoldrick",665476,NaN,https://fr.web.img3.acsta.net/c_310_420/pictur...,u.s.a.,09/06/2021 au 16/06/2021,NaN,warner bros. france,0,...,"English,Latin",NaN,138K,United States,R,"2,702","June 9, 2021",Michael Chaves,6.3,The Conjuring: The Devil Made Me Do It

In [4]:
merged_df.isna().sum()

actors                  0
director_allocine       0
entrees_fr              0
entrees_usa            10
image_urls              0
nationalite             0
semaine_fr              0
semaine_usa            10
studio                  0
timing                  0
title_allocine          0
titre_original          0
title_normalized        0
annee                   0
budget                  0
casting_principal       0
director_dataEda        0
duree                   0
genre                   0
langue                  0
nbre_vote              10
nombre_vote             0
pays                    0
pegi                    0
popularite_score        0
release_date_france     1
scenaristes             0
score                   0
title_dataEda           0
dtype: int64

In [5]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   actors               10 non-null     object
 1   director_allocine    10 non-null     object
 2   entrees_fr           10 non-null     int64
 3   entrees_usa          0 non-null      float64
 4   image_urls           10 non-null     object
 5   nationalite          10 non-null     object
 6   semaine_fr           10 non-null     object
 7   semaine_usa          0 non-null      float64
 8   studio               10 non-null     object
 9   timing               10 non-null     int64
 10  title_allocine       10 non-null     object
 11  titre_original       10 non-null     object
 12  title_normalized     10 non-null     object
 13  annee                10 non-null     object
 14  budget               10 non-null     object
 15  casting_principal    10 non-null     object
 16  director_dataEda     10 non-null     object
 17  duree                10 non-null     object
 18  genre                10 non-null     object
 19  langue               10 non-null     object
 20  nbre_vote            0 non-null      float64
 21  nombre_vote          10 non-null     object
 22  pays                 10 non-null     object
 23  pegi                 10 non-null     object
 24  popularite_score     10 non-null     object
 25  release_date_france  9 non-null      object
 26  scenaristes          10 non-null     object
 27  score                10 non-null     float64
 28  title_dataEda        10 non-null     object
dtypes: float64(4), int64(2), object(23)
memory usage: 2.4+ KB