In [10]:
import pandas as pd


df = pd.read_csv("moviesdata.csv")

# Dropping 'url' and 'salles_premiere_semaine' columns
movies_data_cleaned = df.drop(['url', 'salles_premiere_semaine'], axis=1)

# Keeping rows where both 'acteurs' and 'budget' are not null to avoid incomplete data
movies_data_cleaned = movies_data_cleaned.dropna(subset=['acteurs', 'budget'])

#Dropping duplicate rows based on all columns to ensure unique movie entries
movies_data_cleaned = movies_data_cleaned.drop_duplicates()

movies_data_cleaned.head()

,acteurs,budget,compositeur,date,entrees_premiere_semaine,franchise,genre,pays,producteur,realisateur,remake,studio,titre
2,\r\n Daniel Radclif...,130 000 000 $,John Williams,02/06/2004,2 503 699,Franchise,Fantasy,Etats-Unis,NaN,\r\n Alfons...,NaN,\r\n Warner Bros.,\r\n Harry Potter e...
3,\r\n Robert Pattins...,150 000 000 $,NaN,11/07/2007,2 486 291,Franchise,Fantasy,Etats-Unis,NaN,\r\n David ...,NaN,\r\n Warner Bros.,\r\n Harry Potter e...
6,"\r\n Dany Boon,\r\n...",27 800 000 €,NaN,28/02/2018,2 429 906,NaN,Comédie,France,NaN,\r\n Dany Boon,NaN,\r\n Pathé,\r\n La Ch’tite fam...
9,"\r\n Johnny Depp,\r...",225 000 000 $,Hans Zimmer,02/08/2006,2 708 112,Franchise,Aventure - Action,Etats-Unis,Jerry Brukheimer,\r\n Gore V...,NaN,\r\n Walt Disney Pictures,\r\n Pirates des Ca...
14,\r\n Daniel Radclif...,100 000 000 $,John Williams,04/12/2002,2 728 766,Franchise,Fantasy,Etats-Unis,NaN,\r\n Chris ...,NaN,\r\n Warner Bros.,\r\n Harry Potter e...

In [11]:
movies_data_cleaned.shape

(4536, 13)

### Titre

In [12]:
for index, value in movies_data_cleaned['titre'].items():
    if isinstance(value,str):
        value = value.replace('\r\n','')
        value = value.strip()
        movies_data_cleaned.at[index, 'titre'] = value

### Acteurs

In [13]:
movies_data_cleaned['acteurs'] = movies_data_cleaned['acteurs'].str.strip().replace(r"\r\n", "", regex=True).replace(r"\s+", " ", regex=True) 

movies_data_cleaned.head()

,acteurs,budget,compositeur,date,entrees_premiere_semaine,franchise,genre,pays,producteur,realisateur,remake,studio,titre
2,"Daniel Radcliffe, Emma Watson, Gary Oldman, Al...",130 000 000 $,John Williams,02/06/2004,2 503 699,Franchise,Fantasy,Etats-Unis,NaN,\r\n Alfons...,NaN,\r\n Warner Bros.,Harry Potter et le prisonnier d'Azkaban
3,"Robert Pattinson, Daniel Radcliffe, Emma Watso...",150 000 000 $,NaN,11/07/2007,2 486 291,Franchise,Fantasy,Etats-Unis,NaN,\r\n David ...,NaN,\r\n Warner Bros.,Harry Potter et l'Ordre du Phénix
6,"Dany Boon, François Berléand, Valérie Bonneton...",27 800 000 €,NaN,28/02/2018,2 429 906,NaN,Comédie,France,NaN,\r\n Dany Boon,NaN,\r\n Pathé,La Ch’tite famille
9,"Johnny Depp, Orlando Bloom, Geoffrey Rush, Kei...",225 000 000 $,Hans Zimmer,02/08/2006,2 708 112,Franchise,Aventure - Action,Etats-Unis,Jerry Brukheimer,\r\n Gore V...,NaN,\r\n Walt Disney Pictures,"Pirates des Caraïbes, le secret du coffre maudit"
14,"Daniel Radcliffe, Emma Watson, Kenneth Branagh...",100 000 000 $,John Williams,04/12/2002,2 728 766,Franchise,Fantasy,Etats-Unis,NaN,\r\n Chris ...,NaN,\r\n Warner Bros.,Harry Potter et la chambre des secrets

### Studio

In [14]:
for index, value in movies_data_cleaned['studio'].items():
    if isinstance(value,str):
        value = value.replace('\r\n','')
        value = value.strip()
        movies_data_cleaned.at[index, 'studio'] = value

### Réalisateur

In [15]:
for index, value in movies_data_cleaned['realisateur'].items():
    if isinstance(value,str):
        value = value.replace('\r\n','')
        value = value.replace('-','')
        value = value.strip()
        movies_data_cleaned.at[index, 'realisateur'] = value

movies_data_cleaned.head()

,acteurs,budget,compositeur,date,entrees_premiere_semaine,franchise,genre,pays,producteur,realisateur,remake,studio,titre
2,"Daniel Radcliffe, Emma Watson, Gary Oldman, Al...",130 000 000 $,John Williams,02/06/2004,2 503 699,Franchise,Fantasy,Etats-Unis,NaN,Alfonso Cuaron,NaN,Warner Bros.,Harry Potter et le prisonnier d'Azkaban
3,"Robert Pattinson, Daniel Radcliffe, Emma Watso...",150 000 000 $,NaN,11/07/2007,2 486 291,Franchise,Fantasy,Etats-Unis,NaN,David Yates,NaN,Warner Bros.,Harry Potter et l'Ordre du Phénix
6,"Dany Boon, François Berléand, Valérie Bonneton...",27 800 000 €,NaN,28/02/2018,2 429 906,NaN,Comédie,France,NaN,Dany Boon,NaN,Pathé,La Ch’tite famille
9,"Johnny Depp, Orlando Bloom, Geoffrey Rush, Kei...",225 000 000 $,Hans Zimmer,02/08/2006,2 708 112,Franchise,Aventure - Action,Etats-Unis,Jerry Brukheimer,Gore Verbinski,NaN,Walt Disney Pictures,"Pirates des Caraïbes, le secret du coffre maudit"
14,"Daniel Radcliffe, Emma Watson, Kenneth Branagh...",100 000 000 $,John Williams,04/12/2002,2 728 766,Franchise,Fantasy,Etats-Unis,NaN,Chris Columbus,NaN,Warner Bros.,Harry Potter et la chambre des secrets

### Date

In [16]:
movies_data_cleaned['date'] = movies_data_cleaned['date'].str.strip()
movies_data_cleaned['date'] = pd.to_datetime(movies_data_cleaned['date'], format='%d/%m/%Y')

movies_data_cleaned.head()

,acteurs,budget,compositeur,date,entrees_premiere_semaine,franchise,genre,pays,producteur,realisateur,remake,studio,titre
2,"Daniel Radcliffe, Emma Watson, Gary Oldman, Al...",130 000 000 $,John Williams,2004-06-02,2 503 699,Franchise,Fantasy,Etats-Unis,NaN,Alfonso Cuaron,NaN,Warner Bros.,Harry Potter et le prisonnier d'Azkaban
3,"Robert Pattinson, Daniel Radcliffe, Emma Watso...",150 000 000 $,NaN,2007-07-11,2 486 291,Franchise,Fantasy,Etats-Unis,NaN,David Yates,NaN,Warner Bros.,Harry Potter et l'Ordre du Phénix
6,"Dany Boon, François Berléand, Valérie Bonneton...",27 800 000 €,NaN,2018-02-28,2 429 906,NaN,Comédie,France,NaN,Dany Boon,NaN,Pathé,La Ch’tite famille
9,"Johnny Depp, Orlando Bloom, Geoffrey Rush, Kei...",225 000 000 $,Hans Zimmer,2006-08-02,2 708 112,Franchise,Aventure - Action,Etats-Unis,Jerry Brukheimer,Gore Verbinski,NaN,Walt Disney Pictures,"Pirates des Caraïbes, le secret du coffre maudit"
14,"Daniel Radcliffe, Emma Watson, Kenneth Branagh...",100 000 000 $,John Williams,2002-12-04,2 728 766,Franchise,Fantasy,Etats-Unis,NaN,Chris Columbus,NaN,Warner Bros.,Harry Potter et la chambre des secrets

### Budget

In [17]:
movies_data_cleaned['budget'] = movies_data_cleaned['budget'].str.replace('[\$,€]', '', regex=True).str.replace(' ', '').str.replace('?', '')
movies_data_cleaned['budget'] = pd.to_numeric(movies_data_cleaned['budget'], errors='coerce').fillna(0).astype(int)

movies_data_cleaned.head()

,acteurs,budget,compositeur,date,entrees_premiere_semaine,franchise,genre,pays,producteur,realisateur,remake,studio,titre
2,"Daniel Radcliffe, Emma Watson, Gary Oldman, Al...",130000000,John Williams,2004-06-02,2 503 699,Franchise,Fantasy,Etats-Unis,NaN,Alfonso Cuaron,NaN,Warner Bros.,Harry Potter et le prisonnier d'Azkaban
3,"Robert Pattinson, Daniel Radcliffe, Emma Watso...",150000000,NaN,2007-07-11,2 486 291,Franchise,Fantasy,Etats-Unis,NaN,David Yates,NaN,Warner Bros.,Harry Potter et l'Ordre du Phénix
6,"Dany Boon, François Berléand, Valérie Bonneton...",27800000,NaN,2018-02-28,2 429 906,NaN,Comédie,France,NaN,Dany Boon,NaN,Pathé,La Ch’tite famille
9,"Johnny Depp, Orlando Bloom, Geoffrey Rush, Kei...",225000000,Hans Zimmer,2006-08-02,2 708 112,Franchise,Aventure - Action,Etats-Unis,Jerry Brukheimer,Gore Verbinski,NaN,Walt Disney Pictures,"Pirates des Caraïbes, le secret du coffre maudit"
14,"Daniel Radcliffe, Emma Watson, Kenneth Branagh...",100000000,John Williams,2002-12-04,2 728 766,Franchise,Fantasy,Etats-Unis,NaN,Chris Columbus,NaN,Warner Bros.,Harry Potter et la chambre des secrets

### Nombre d'entrées

In [18]:
movies_data_cleaned['entrees_premiere_semaine'] = movies_data_cleaned['entrees_premiere_semaine'].str.replace(' ', '').astype(int) 

movies_data_cleaned.head()

,acteurs,budget,compositeur,date,entrees_premiere_semaine,franchise,genre,pays,producteur,realisateur,remake,studio,titre
2,"Daniel Radcliffe, Emma Watson, Gary Oldman, Al...",130000000,John Williams,2004-06-02,2503699,Franchise,Fantasy,Etats-Unis,NaN,Alfonso Cuaron,NaN,Warner Bros.,Harry Potter et le prisonnier d'Azkaban
3,"Robert Pattinson, Daniel Radcliffe, Emma Watso...",150000000,NaN,2007-07-11,2486291,Franchise,Fantasy,Etats-Unis,NaN,David Yates,NaN,Warner Bros.,Harry Potter et l'Ordre du Phénix
6,"Dany Boon, François Berléand, Valérie Bonneton...",27800000,NaN,2018-02-28,2429906,NaN,Comédie,France,NaN,Dany Boon,NaN,Pathé,La Ch’tite famille
9,"Johnny Depp, Orlando Bloom, Geoffrey Rush, Kei...",225000000,Hans Zimmer,2006-08-02,2708112,Franchise,Aventure - Action,Etats-Unis,Jerry Brukheimer,Gore Verbinski,NaN,Walt Disney Pictures,"Pirates des Caraïbes, le secret du coffre maudit"
14,"Daniel Radcliffe, Emma Watson, Kenneth Branagh...",100000000,John Williams,2002-12-04,2728766,Franchise,Fantasy,Etats-Unis,NaN,Chris Columbus,NaN,Warner Bros.,Harry Potter et la chambre des secrets